### DISCUSSION TITLE
How to set up charging on demand?

### DISCUSSION THREAD

**Discussion by sshaikh** [bimmerconnected/bimmer_connected#628] [Q&A] [answered]
The HA docs imply you can use the `charging mode` to emulated charging on demand. We don't use schedules or departure times, but after trying some dummy settings we still can't figure out how to configure or use the settings to charge on demand via HA.

Any tips?

**Comment by gerard33** [comment, marked as answer]
You can use `select.[vehicle]_charging_mode` to change the charging mode of your car.

Example automation to set the mode to immediate charging
```yaml
- service: select.select_option
  target:
    entity_id: select.[vehicle]_charging_mode
  data:
    option: immediate_charging
```
