### ISSUE TITLE
Max_fuel should include unit for HA sensor

### ISSUE THREAD

**Issue by robthebold** [bimmerconnected/bimmer_connected#114]
Issue: 

bimmer_connected is not returning a unit of measure with max_fuel, so HA displays a unitless value for max_fuel. Given the value I see, I believe that it's reporting SI liters. The sensor on the HA dashboard shows the circle with out a unit at the bottom. My BMW is a '17 i3 94 with Rex. (north_america, USA)

Expected behavior:

bimmer_connected should return a value with a unit of measure so that HA can properly show a  localized value of max_fuel. (Sort of localized -- HA itself lacks US units, but that problem is out of this scope)

**Home Assistant version**
0.98.1

**Screenshots**
![Screenshot_20190904_082029](https://user-images.githubusercontent.com/38596885/64259256-5d0a3880-ceee-11e9-9f68-90e22f919b1c.png)

![Screenshot_20190904_081932](https://user-images.githubusercontent.com/38596885/64259306-74492600-ceee-11e9-807a-ad2bd31089e3.png)

**My config.yaml**
```
bmw_connected_drive:
    name:
        username: USERNAME_BMW_CONNECTED_DRIVE
        password: PASSWORD_BMW_CONNECTED_DRIVE
        region: "north_america"
````
