### ISSUE TITLE
MY2018 F15 BMW X5 xDrive 35i

### ISSUE THREAD

**Issue by THATDONFC** [bimmerconnected/bimmer_connected#159]
**Your config.yaml**
```yaml
bmw_connected_drive:
  name_of_car:
    username: USERNAME_BMW_CONNECTED_DRIVE
    password: PASSWORD_BMW_CONNECTED_DRIVE
    region: "north_america"
````

**Output of bimmer_connected fingerprint**
[status_0.txt](https://github.com/bimmerconnected/bimmer_connected/files/4253911/status_0.txt)
[vehicles_0.txt](https://github.com/bimmerconnected/bimmer_connected/files/4253913/vehicles_0.txt)

*NOTE: It might take me a while to respond on GitHub (I only maintain this in my free time), but I will respond.*
