### ISSUE TITLE
MY2020 BMW G05 X5 45e fingerprint

### ISSUE THREAD

**Issue by nilsvdb82** [bimmerconnected/bimmer_connected#166]
**Your config.yaml**

```
bmw_connected_drive:
  name_of_car:
    username: USERNAME_BMW_CONNECTED_DRIVE
    password: PASSWORD_BMW_CONNECTED_DRIVE
    region: "rest_of_world"
```

**Output of bimmer_connected fingerprint**
[status_0.txt](https://github.com/bimmerconnected/bimmer_connected/files/4383457/status_0.txt)
[status_1.txt](https://github.com/bimmerconnected/bimmer_connected/files/4383458/status_1.txt)
[vehicles_0.txt](https://github.com/bimmerconnected/bimmer_connected/files/4383459/vehicles_0.txt)

note: My previous F25 x20d is also included in the fingerprint
