### ISSUE TITLE
MY2019 BMW M135i - Fingerprint

### ISSUE THREAD

**Issue by sincze** [bimmerconnected/bimmer_connected#168]
```yaml
bmw_connected_drive:
  name_of_car:
    username: USERNAME_BMW_CONNECTED_DRIVE
    password: PASSWORD_BMW_CONNECTED_DRIVE
    region: rest_of_world
````

[vehicles_0.txt](https://github.com/bimmerconnected/bimmer_connected/files/4398983/vehicles_0.txt)
[status_0.txt](https://github.com/bimmerconnected/bimmer_connected/files/4398984/status_0.txt)
